### ISSUE TITLE
fingerprint issue in marshmallow

### ISSUE THREAD

**Issue by sharmaratdrive** [multidots/android-fingerprint-authentication#4]
the fingerprint is only working in noughat. marshmallow hardware not recognize

**Comment by kevalpatel2106** [comment]
@sharmaratdrive Can you please paste your device specifications and crash logs?

**Comment by hwalidh** [comment]
@kevalpatel2106 
Please I need your help as soon as possible.
I am currently developing an application that uses the fingerprint reader.
I use a predefined method that lets me know whether the smartphone has a fingerprint sensor or not fingerprintManagerCompat.isHardwareDetected (); The problem is that method returns FALSE while my OPPO F1s OS version android 5.1 API22 has a fingerprint reader.
What should I do? {:5_155:} 

PS: I took permission to use the fingerprint reader <uses-permission android:name="android.permission.USE_FINGERPRINT"/>.
Thank you.

**Comment by kevalpatel2106** [comment]
@hwalidh 
Fingerprint scanning support was added in android 6.0. So android version older than 6.0, won't support fingerprint authentication. 

See the behavior changes for Android M : https://developer.android.com/about/versions/marshmallow/android-6.0.html#fingerprint-authentication

**Comment by hwalidh** [comment]
@kevalpatel2106  yes but there is a FingerprintManagerCompat Class for android version older than 6.0.
Despite that, it does not work.

**Comment by kevalpatel2106** [comment]
FingerprintManagerCompat class is just to make the programming easy. It checks for the device API level internally. So, you don't have to check for the API level everywhere in your code. Otherwise, it is not porting the real fingerprint scanning functionality to older android versions.

As per the [documentation](https://developer.android.com/reference/android/support/v4/hardware/fingerprint/FingerprintManagerCompat.html): 

> A class that coordinates access to the fingerprint hardware.
> On platforms before M, this class behaves as there would be no fingerprint hardware available.

**Comment by qaz349293703** [comment]
hi, my xiaomi 5 phone ,API 23 ,android 6 . but FingerprintManagerCompat.isHardwareDetected and FingerprintManagerCompat.hasEnrolledFingerprints always return false .  really it  should return true ,why ?????  because the documentation is said the android before M can not return true. but now my phone is Android M

**Comment by hwalidh** [comment]
@kevalpatel2106 if I increase the version of my android OS 5.1 to OS 6.0 manually, will it work?
